### ISSUE TITLE
GPU Code Generation

### ISSUE THREAD

**Issue by fredrikbk** [tensor-compiler/taco#129]
We need to generate GPU kernels. As a first step we're planning to generate CUDA code and compile it with our current system-compiler scheme (Nvidia has graciously donated GPUs we'll work with).

The target for GPU support in taco is mid April.

Open questions:
- [ ] How should we design the device API to move tensors to and from GPU memories?
- [ ] What formats will work best on GPUs?
- [ ] What scheduling constructs are needed on GPUs (see #127)?
- [ ] What does assembly code look like on GPUs?
- [ ] Do users need other backends than CUDA (e.g., OpenCL, OpenACC, or Metal)?

**Comment by ShadenSmith** [comment]
Concerning sparse formats, I don't know that there has been enough work in that area yet to say that one format will work best.

There is [F-COO](https://arxiv.org/pdf/1705.09905.pdf) -- it gets good speedup over CSF on CPU when the tensor is mostly dense (e.g., BrainQ which is 90% dense when empty slices are removed).

DFacTo and its family of methods like [ReFacTo](https://www.researchgate.net/profile/Tyler_Simon/publication/317949817_Performance_Challenges_for_Heterogeneous_Distributed_Tensor_Decompositions/links/59caa9b945851556e97e2dbb/Performance-Challenges-for-Heterogeneous-Distributed-Tensor-Decompositions.pdf) are based on matricized tensors. That lets you build on the much more mature world of sparse matrix computations. Though matricized tensors have limitations once their modes get long.

I think I have heard whispers of Nvidia including sparse tensor factorization in an upcoming cuSPARSE release? The last I heard, they were looking at matricized tensors in order to utilize their existing SpMV infrastructure.

**Comment by fredrikbk** [comment]
I see, we should study F-COO (@stephenchouca). We will support the same formats on GPU as on CPU, so it should become possible to study which formats make sense in different cases. @stephenchouca  will soon merge in support for many new formats in taco, including coordinates and generalizations of ell and dia.

Agreed about the matricizarion; especially when there’s support for specifying lower bit widths for the indices.

**Comment by eric-haibin-lin** [comment]
I'm curious if there's any update on the GPU codegen roadmap?

**Comment by fredrikbk** [comment]
Hi, yes, I'll be starting implement the GPU backend in August.  We have a project together with Nvidia and this will be part of it.  We have the hardware and I just need to get through the rewrite of the lowering machinery and then this is next.

**Comment by Oblynx** [comment]
Hi, is there any update on this, now that as I understand the lowering work is done?

**Comment by fredrikbk** [comment]
Hi @oblynx thank you for checking in. Out of curiosity, do you have a specific application you are interested in?

The lowering machinery unfortunately got delayed but @rsenapps have been working on a gpu backend in parallel.

@rsenapps do you have a rough estimate for the gpu backend?

My best estimate for the new lowering backend is at the moment the end of the year.

**Comment by Oblynx** [comment]
Thanks for your great work! Using GPUs is an optimization for my application, not a primary requirement. If my application is to be deployed though in the future, they may prove crucial, so it is nice to know that there's progress and a clear goal on this one.
My project is the expression of a set of algorithms in sparse tensor algebra, implemented in Julia. My primary motivation is the clean and simple expression of the algorithms, and the index notation that taco speaks is a great fit, as the primary data structures that I use are 4th order sparse tensors.

I depend rather on @peterahrens work for this, who will likely have a beta tester immediately. By the way, @peterahrens how is tortilla progressing?
