### ISSUE TITLE
How to turn on parallel taco

### ISSUE THREAD

**Issue by MeBlueDolphin** [tensor-compiler/taco#131]
Hi,
   I am testing SPMV with TACO.  How do I turn on parallelism?
Thank you,
Ismail Bustany

**Comment by xysmlx** [comment]
I noticed that the generated codes have the openmp configuration. So you can try to add the openmp compile flag -fopenmp in the compile stage. I am not sure whether it can work or not.

**Comment by shoaibkamil** [comment]
taco generates OpenMP pragmas when it is safe to do so.  If you're including taco-generated code in your own app, then adding the appropriate OpenMP compiler flags should be sufficient (e.g. `-fopenmp` if you're using GCC).

If you're using taco as a library, then you can change the backend compiler flags by setting the environment variable `TACO_CFLAGS`.  The default flags are `-O3 -ffast-math -std=c99`, so you probably want something like
```
export TACO_CFLAGS="-O3 -ffast-math -std=c99 -fopenmp"
```

**Comment by Asterix9000** [comment]
Hello, 
I know that this is several years after this was closed, but I have been having some difficulty getting Taco to run in parallel as well. Today I have built and installed Taco via: `cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${HOME}/taco/10_1_20/taco/install -DOPENMP=ON ..`

I then copied the MTTKRP example from the documentation website, changed it generate a random tensor instead of using the nell-2 database, ran `export TACO_CFLAGS="-O3 -ffast-math -std=c99 -fopenmp"`, set OMP_NUM_THREADS to 4, set LD_LIBRARY_PATH to point to the taco library and then compiled with: `g++ -std=c++11 -O3 -fopenmp -DNDEBUG -DTACO  -I ../taco/install/include -L/home/taco/10_1_20/taco/install/lib mttkrp.cpp -o mttkrp -ltaco`

However, I am not seeing any speedup. I am using gcc/9.2.0. I was hoping that you might be able to help me with this issue.
