### ISSUE TITLE
Is there a Inverse function for 2D-Tensors?

### ISSUE THREAD

**Issue by ClmnsRck** [tensor-compiler/taco#221]
The title says it all, but is there a inverse operator, like numpys `pow(-1)`?

**Comment by fredrikbk** [comment]
Do you want to independently invert every component (e.g. `10` becomes `0.1`), or do you want to invert a matrix as in gaussian elimination?

For component-wise inverses our [new lowering framework](https://github.com/tensor-compiler/taco/projects/3) will let us build support for arbitrary component-wise operations.

For matrix inversion, you can build some Krylov methods such as CG on top of taco, but generating general solves is a research problem (that I do plan to work on in the future, but not promises for the timeline).  However, we are building an interoperation API with Eigen so that you can convert 2d tensors to Eigen matrices and solve them with Eigen built-in functions.

**Comment by ClmnsRck** [comment]
I would like Matrix inversion. But is not a big deal if it does not exist. Thanks

One last Question: When you do the Expression building for a Tensor e.g. `A(i,j)=B(i,k)*C(k,j);` what happens there? because i am benchmarking it kind of and would like to know if i should benchmark that part too...

**Comment by fredrikbk** [comment]
Ahh, sorry, our agenda is to generate code and we do not yet know how to do that for matrix inverses (future research).  You should therefore use another library for that that has a hand-coded version of the inverse you need.

In the current set of API's nothing really happen when you do that, other than some objects are created and assigned to a slot in `A`. The work happens during `compile`, `assemble`, and `compute`. The work pertaining to computing your results happen during assemble and compile.  Whether you should also time the expression and the compile depends on what the situation is.  If your use case is to use each kernel once then the cost of them matters.  If you'll use each kernel multiple times then it amortizes away and doesn't matter.

@oicirtap is, however, building a new lazy API where you don't need to call `compile`, `assemble`, or `compute`, but where these happen behind the scenes.  With this API the performance semantics of each functions becomes a lot more murky as compilation and computation can happen at any call.  The new API, however, will not be recommended for performance evaluation.

**Comment by ClmnsRck** [comment]
O, so if i just want to test the performance `A.evaluate();` is the thing to do? 

I am using Eigen already, that works for me, because of that, its not a big deal that taco misses the inverse-function
