### ISSUE TITLE
[help] When trying to reporduce SDDMM-ex. the Code fails

### ISSUE THREAD

**Issue by ClmnsRck** [tensor-compiler/taco#222]
When i was trying to reproduce the SDDMM example, i forgot to set the ordering of D to colum-major and got segmentation-faults ... why is that, shouldnt it work anyways?

**Comment by oicirtap** [comment]
The reason for this is that the code generated by taco requires traversing matching dimensions of different tensors in a computation in the same order. For example, in the simple expression `A(i,j) = B(i,j)`, if both matrices are in row major, the generated code can traverse the `i` dimension, followed by the `j` dimension. On the other hand, if `B` is column major, then `B` requires `j` to be traversed before `i` instead (Since this is the order in which the data is structured). The seg-fault is likely triggered because the code assumes that D is in column-major format when it's not.

I believe the Debug build for taco contains assertions which identify this kind of dimension ordering mismatch, but the release version likely does not perform the required assertions to catch this.

The new release for taco will be able to detect this dimension mismatch and transpose tensors as necessary for the computation to proceed. This will be a temporary measure to allow for computations on tensors with incompatible orderings. We are also working on developing the theory behind compiling code to transpose tensors.

I hope this helps clarify your doubt.
