### ISSUE TITLE
Recuring tensor-operations

### ISSUE THREAD

**Issue by ClmnsRck** [tensor-compiler/taco#224]
When doing calculations for artificial neural networks for example, would it be possible to reuse the generated code? Meaing that, because the structure of a ANN is static, that i could do multiple steps of these with one compile-call from `taco`. And the data would just be changed directly in memory?

**Comment by stephenchouca** [comment]
You can reuse the generated code by calling `compile`, `assemble`, and `compute` separately instead of calling `evaluate`, which under the hood simply calls the first three methods. So something like:

```c++
Tensor<double> A, B, C;
IndexVar i, j;
A(i,j) = B(i,j) + C(i,j);

// initialize B and C with some data

A.compile(); // generates code to perform addition
A.assemble(); // computes sparsity structure of A
A.compute(); // computes values of A

// initialize B and C with some new data

A.assemble(); // computes new sparsity structure of A
A.compute(); // computes new values of A
```

If you know that the sparsity structure of the output will not change when you reinitialize the inputs with new data, then you can omit the second call to `assemble` as well:

```c++
Tensor<double> A, B, C;
IndexVar i, j;
A(i,j) = B(i,j) + C(i,j);

// initialize B and C with some data

A.compile(); // generates code to perform addition
A.assemble(); // computes sparsity structure of A
A.compute(); // computes values of A

// initialize B and C with some new data but keeping the sparsity structures of B and C identical

A.compute(); // just compute the new values of A, since we know that A's 
             // sparsity structure cannot have changed
```

**Comment by ClmnsRck** [comment]
Thank you, thats great. I'll leave it to you if this should remain open, or can be closed :smiley:
