### ISSUE TITLE
questions about code generation

### ISSUE THREAD

**Issue by zjin-lcf** [tensor-compiler/taco#293]
The generated codes below show that only one of the three tensors for the expression "a(i) = b(i) + c(i)" is allocated using USM. What happened to the other two tensors ?  Please clarify the code generation process:  Does your compiler generate a complete cuda program ?  If not, is there a flag or way to display an entire cuda program for understanding the execution of a cuda program ?  Thank you!

```
int assemble(taco_tensor_t *a, taco_tensor_t *b, taco_tensor_t *c) {
  int a1_dimension = (int)(a->dimensions[0]);
  double* __restrict__ a_vals = (double*)(a->vals);
  int a_vals_size = a->vals_size;
  int b1_dimension = (int)(b->dimensions[0]);

  for (int32_t ib = 0; ib < b1_dimension; ib++) {
  }

  gpuErrchk(cudaMallocManaged((void**)&a_vals, sizeof(double) * a1_dimension));
  a_vals_size = a1_dimension;

  a->vals = (uint8_t*)a_vals;
  a->vals_size = a_vals_size;
  return 0;
}

int evaluate(taco_tensor_t *a, taco_tensor_t *b, taco_tensor_t *c) {
  int a1_dimension = (int)(a->dimensions[0]);
  double* __restrict__ a_vals = (double*)(a->vals);
  int b1_dimension = (int)(b->dimensions[0]);
  double* __restrict__ b_vals = (double*)(b->vals);
  double* __restrict__ c_vals = (double*)(c->vals);

  gpuErrchk(cudaMallocManaged((void**)&a_vals, sizeof(double) * a1_dimension));

  for (int32_t ib = 0; ib < b1_dimension; ib++) {
    a_vals[ib] = b_vals[ib] + c_vals[ib];
  }

  a->vals = (uint8_t*)a_vals;
  return 0;
}
```

In addition, when using nvprof to profile the sample on a P100 GPU, I don't observe the kernel execution. I am not sure if this is expected.  
```
nvprof ./bin/taco-tensor_times_vector
==23638== NVPROF is profiling process 23638, command: ./bin/taco-tensor_times_vector
A0 (2x3) ({dense},{compressed}; 0,1):
dense (0):
  [2]
compressed (1):
  [0, 1, 2]
  [0, 2]
[4, 23]
==23638== Profiling application: ./bin/taco-tensor_times_vector
==23638== Profiling result:
No kernels were profiled.
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
      API calls:   98.29%  204.40ms        78  2.6205ms  5.3600us  202.82ms  cudaMallocManaged
                    1.03%  2.1325ms         4  533.13us  501.52us  567.24us  cuDeviceTotalMem
                    0.29%  602.01us       379  1.5880us     127ns  58.412us  cuDeviceGetAttribute
                    0.18%  366.06us         3  122.02us  111.02us  131.38us  cudaGetDeviceProperties
                    0.10%  210.55us        15  14.036us  8.9810us  35.341us  cudaFree
                    0.08%  172.07us         4  43.018us  13.907us  68.840us  cuDeviceGetName
                    0.02%  39.708us         3  13.236us  9.8410us  15.163us  cuModuleUnload
                    0.00%  9.1190us         1  9.1190us  9.1190us  9.1190us  cuDeviceGetPCIBusId
                    0.00%  6.1220us         3  2.0400us  1.1450us  3.4730us  cuInit
                    0.00%  6.1180us         3  2.0390us  1.2340us  3.6390us  cuDriverGetVersion
                    0.00%  3.2750us         6     545ns     206ns     989ns  cuDeviceGetCount
                    0.00%  2.6910us         5     538ns     198ns     699ns  cuDeviceGet
                    0.00%  1.5020us         4     375ns     312ns     440ns  cuDeviceGetUuid
                    0.00%  1.0300us         3     343ns     226ns     520ns  cuDevicePrimaryCtxRelease
```

**Comment by RSenApps** [comment]
Hi, could you provide more details in how you generated the code you pasted in your issue? There are many ways to use TACO and it appears that the way you are generating this code is not properly parallelizing the kernel onto GPU.

Other ways to generate full CUDA kernels that you may find helpful are:
1. The command line tool such as this command, which uses a very simple GPU schedule that will probably not provide high performance for most kernels, but is easy to use:
`bin/taco "a(i) = b(i) + c(i)" -cuda -write-source=vecadd.cu`

2. [https://github.com/tensor-compiler/taco/blob/master/test/tests-scheduling-eval.cpp](url) has many examples of how to use the scheduling language to generate high-performance GPU kernels. The test case (generate_evaluation_files) `https://github.com/tensor-compiler/taco/blob/01c269b29a29c56b0a224ce6b2c1cb3c87e5c3b0/test/tests-scheduling-eval.cpp#L1447` has examples of how to generate full CUDA files instead of directly performing the computation within the TACO library.

Hope that helps, please let me know if you have any further questions.

**Comment by zjin-lcf** [comment]
first of all, I found that I am not using the latest version of taco.  It is interesting to see the difference in the generated codes.

After cloning and building your repo 
1.  I tried your command, so the output of the command: bin/taco "a(i) = b(i) + c(i)" -cuda -write-source=vecadd.cu  is partially display below: 

May you reproduce the issues (only one of the three tensors is allocated with USM) mentioned before ?  

Thanks
 
```
160 int assemble(taco_tensor_t *a, taco_tensor_t *b, taco_tensor_t *c) {
161   int a1_dimension = (int)(a->dimensions[0]);
162   double* __restrict__ a_vals = (double*)(a->vals);
163
164   gpuErrchk(cudaMallocManaged((void**)&a_vals, sizeof(double) * a1_dimension));
165
166   a->vals = (uint8_t*)a_vals;
167   return 0;
168 }
169
170 __global__
171 void evaluateDeviceKernel0(taco_tensor_t * __restrict__ a, taco_tensor_t * __restrict__ b, taco_tensor_t * __restrict__ c){
172   double* __restrict__ a_vals = (double*)(a->vals);
173   double* __restrict__ b_vals = (double*)(b->vals);
174   int c1_dimension = (int)(c->dimensions[0]);
175   double* __restrict__ c_vals = (double*)(c->vals);
176
177   int32_t i27 = blockIdx.x;
178   int32_t i28 = (threadIdx.x % (256));
179   if (threadIdx.x >= 256) {
180     return;
181   }
182
183   int32_t i = i27 * 256 + i28;
184   if (i >= c1_dimension)
185     return;
186
187   a_vals[i] = b_vals[i] + c_vals[i];
188
189 }
190
191 int evaluate(taco_tensor_t *a, taco_tensor_t *b, taco_tensor_t *c) {
192   int a1_dimension = (int)(a->dimensions[0]);
193   double* __restrict__ a_vals = (double*)(a->vals);
194   int c1_dimension = (int)(c->dimensions[0]);
195
196   int32_t a_capacity = a1_dimension;
197   gpuErrchk(cudaMallocManaged((void**)&a_vals, sizeof(double) * a_capacity));
198
199   evaluateDeviceKernel0<<<(c1_dimension + 255) / 256, 256>>>(a, b, c);
200   cudaDeviceSynchronize();
201
202   a->vals = (uint8_t*)a_vals;
203   return 0;
204 }


```

**Comment by zjin-lcf** [comment]
Do you think it is helpful to add an taco commandline option to generate full CUDA files instead of directly performing the computation within the TACO library  ?

**Comment by RSenApps** [comment]
Only result tensors are allocated as it is expected that the caller passes pointers to tensors that have already been properly allocated (the TACO library will make sure to perform this allocation for you). This is to prevent unnecessary additional allocations when performing multiple computations with the same tensors.

The tensor_times_vector example doesn't parallelize onto GPU because it writes into a sparse result, which can not be easily parallelized as it requires parallel sparse assembly. 

I recommend starting with one of the examples in the tests-scheduling-eval.cpp file. If you would like to quickly run a kernel on gpu you can use:
`bin/taco "a(i) = b(i) + c(i)" -time -cuda -g=b:d -g=c:d`
To run one of the tests you can use:
`bin/taco-test --gtest_filter="scheduling_eval.spmvGPU"`

Also if you are hoping to just get an idea of how our performance is on GPU, you can refer to my (now slightly out-of-date) master's thesis: http://rsenapps.com/senanayake-thesis.pdf If you would like to email at rsen@mit.edu, I could send a preprint of a paper with updated results.

Finally, I agree that it would be nice to be able to generate fully self-contained cuda kernels from the command line, but maybe an intermediate solution would be to make some gpu examples more easily accessible? We also plan to release a benchmarking suite in the near future that will allow quickly running TACO generated kernels on large tensor repositories.

**Comment by zjin-lcf** [comment]
Thanks for explaining the USM allocation and the links. Congratulations on your achievement!

My understanding of generating (dumping) a cuda program contains, for example, a main function. In other words, a standalone cuda program.  However, I found that the test case (generate_evaluation_files) only generates kernel wrappers (i.e. a function to launch a cuda kernel) and kernels for each test (e.g. spmv). Is that right ?   If that is right, I'd like to know where I can find the remaining part of a "standalone" cuda program without fully understanding every details of your software.

**Comment by RSenApps** [comment]
TACO currently does not support "dumping" full runnable programs. It can either be used to generate the important kernels or it can be used as a library.

When you choose to not use it as a library, it is required to write code around the generated kernels to allocate and load the input tensors that are passed to the kernels. Given sparse vectors this should be very fast code to write (and allows you to integrate the kernels with other existing code that you have), but in general it is recommended to use TACO as a library (like in the spmvGPU test case) when you need more flexibility.

In the benchmarking suite we are working on, we have code that wraps the generated kernels with timers and loading of tensors. If you email me I can provide this code as an example.

Hope that is helpful. Maybe if you give me a better idea of what in particular you are hoping to use TACO for I can provide some more specific suggestions or examples.

**Comment by zjin-lcf** [comment]
It is helpful!  I will contact you by emails
