### ISSUE TITLE
taco -cuda doesn't always produce cuda code

### ISSUE THREAD

**Issue by trevor-vincent** [tensor-compiler/taco#341]
Thank you for the cool library! Here is an issue I ran into:

taco "a(i,j) = c(n)*B(i,j,n) "  -cuda 

produces cuda code

taco "a(i,j) = c(n)*B(n,i,j)" -cuda   

produces C++ code

**Comment by RSenApps** [comment]
TACO by default attempts to use a simple parallel schedule to generate CUDA code which is to parallelize the outer loop over GPU blocks and threads. However this schedule is not very efficient for most cases (especially on GPU) and so usually we expect the user to use the scheduling language to write a correct schedule.

In this case, TACO doesn't parallelize your code because it uses the default loop ordering of n -> i -> j. Parallelizing the outer loop would cause for scattering behavior that would require synchronization and therefore TACO conservatively leaves the code unscheduled.

You could explicitly reorder the loops and then apply the default schedule with:

> taco "a(i,j)=c(n)*B(n,i,j)" -s="reorder(i,j,n)" -s="split(i,i0,i1,256)" -s="parallelize(i0,GPUBlock,NoRaces)" -s="parallelize(i1,GPUThread,NoRaces)"

or you could keep the same loop ordering and use atomic operations for synchronization:

> taco "a(i,j)=c(n)*B(n,i,j)"  -s="split(n,n0,n1,256)" -s="parallelize(n0,GPUBlock,NoRaces)" -s="parallelize(n1,GPUThread,Atomics)"

or you could do many other interesting schedules that tile the computation efficiently. Please see our OOPSLA 2020 paper for details of how to use the scheduling language: https://doi.org/10.1145/3428226

**Comment by trevor-vincent** [comment]
Thanks for the detailed answer!
