### ISSUE TITLE
Taco should generate dimension-size-independent code

### ISSUE THREAD

**Issue by shoaibkamil** [tensor-compiler/taco#44]
Currently, the code generation uses dimension sizes in the code.  We should (perhaps optionally) also generate dimension-size-independent code, so that the same code can be used to e.g. do `spmv()` for a 10x25 matrix as well as a 100x25 matrix, etc.

**Comment by fredrikbk** [comment]
I have two designs in mind that satisfies @peterahrens request.

The first design, which I like better, hard-codes dimensions by default. However, the compile machinery can take an optional `set<pair<TensorBase, int>> sizeIndependentDimensions` that are dimensions that should not be hard-coded. This is a bit awkward to use, as it is a side-api, but I cannot see why a user of the regular library needs to do it. It seems like something only code generators would use.

The second design is to create a `Dimension` class that is passed to the `Tensor` constructor. `Dimension` stores the dimension size and a kind, which can be either hard coded or dimension-size independent. Dimension would have an implicit constructor that converts an int to it, so that it is backwards compatible. Examples (something like):
```
Tensor<double> A({10, 42});
Tensor<double> A({Dimension(10, DimensionSizeIndependent), 42});
```
The latter example ensures the first dimension is not hard-coded.

**Comment by peterahrens** [comment]
I suppose the user may want to control how many kernels are generated. If they do the same computation many times with different block sizes, they might want to reuse code instead of generating each time. Is there no way to distinguish dimensions based on the types passed to the constructor? Something like this:
`Tensor<double> A(SizeIndependent(), 42);`

**Comment by peterahrens** [comment]
Another question: does your first idea apply to the case where we want to permute which dimensions are stored on which level?

**Comment by peterahrens** [comment]
Ah, I misunderstood the second option. I think that having an implicit constructor that sets DimensionSizeDependent and an explicit constructor which sets DimensionSizeIndependent would likely provide the nicest interface. The user could then say something like:
`Tensor<double> A(variable(10), 42)`
or if they wanted to be explicit:
`Tensor<double> A(variable(10), fixed(42))`

However, if you think that users shouldn't care about setting dimension size, then any interface will do. I suspect some users may want this relatively non-invasive option.

**Comment by fredrikbk** [comment]
365a8bf6e43dd25ee7d6f15bbe08c982f474268d adds size-independent code emission (in all cases). This is nice for the online tool, but may have caused performance regression for blocked code, where dimensions are small and it may matter that the backend compiler knows the exact sizes.

The above discussion raises two issues that I have opened separately.
1. We should provide an API to hard-code dimension sizes in the emitted code. This should be the default behavior in the normal C++ work flow (#71)
2. The user should be able to re-use compiled kernels across multiple expressions.

@peterahrens in the current C++ API you can't reuse kernels across expressions. So it doesn't really make sense for users to specify whether a `Tensor` dimension is variable or not, because dimensions are immutable state of a `Tensor`. So really, in this flow it makes sense to always hard-code constants. However, as you point out it should be possible to reuse kernels across expressions that only differ in their operands. Let's discuss this in issue #
