### ISSUE TITLE
Tiling the position space of the row coordinates

### ISSUE THREAD

**Issue by iquitap** [tensor-compiler/taco#493]
In the paper "A Unified Iteration Space Transformation Framework for Sparse and Dense Tensor Algebra", the authors explore a number of interesting approaches for sparse and dense loop transformations.

Figures 5-7 in the paper show three tiling methods for sparse data. Assuming that the vertical loop is the i-loop, the horizontal loop is the j-loop, the default order of the loops is i->j, and the format of the data is CSR, I refer to the TACO document, and Figure 5 can be considered as implemented by "split(i, i1, i2)", and Figure 6 can be considered as implemented by "fuse(i,j,m); pos(m, mpos); split(mpos)".

Now I am confused, how to implement "Tiling the position space of the row coordinates." shown in Figure 7 according to TACO's API? I hope to get some guidance and help.

Any kind reply is highly appreciated.
<img width="625" alt="WX20211214-154533@2x" src="https://user-images.githubusercontent.com/11996844/145954760-34d21399-4a22-4b7c-90d8-cf6956de18a6.png">

**Comment by RSenApps** [comment]
Hi @iquitap,

Good question and you correctly notice that if the matrix is stored CSR then there is no good way to partition like in Figure 7. This is because in CSR the rows are stored dense so the information needed to do this partition is not readily available. If however, you take a format that stores the rows in a compressed format (like DCSR), this type of splitting is possible with pos(i, ipos); split/divide(ipos).

Here is some sample code that demonstrates the Figure 7 split:
http://tensor-compiler.org/codegen.html?expr=A(i,j)=B(i,j)&format=A:ss:0,1;B:ss:0,1&sched=pos:i:ipos:B;split:ipos:ipos0:ipos1:2

And as a comparison here is the Figure 5 split (with DCSR, the code is much simpler for CSR):
http://tensor-compiler.org/codegen.html?expr=A(i,j)=B(i,j)&format=A:ss:0,1;B:ss:0,1&sched=split:i:i0:i1:3

Let me know if you have any additional questions.

**Comment by iquitap** [comment]
I understand. Your answer is very clear and helpful, thank you very much!
