### ISSUE TITLE
Failed tests on format conversion

### ISSUE THREAD

**Issue by zhang677** [tensor-compiler/taco#534]
I've tried to reproduce the results in Automatic Generation of Efficient Sparse Tensor Format Conversion Routines (PLDI 20'). But I met with these errors:

CSR_CSC: Not supported
[http://tensor-compiler.org/codegen.html?expr=A(i,j)%20=%20B(i,j)%20&format=A:ds:0,1;B:ds:1,0](http://tensor-compiler.org/codegen.html?expr=A(i,j)%20=%20B(i,j)%20&format=A:ds:0,1;B:ds:1,0)

CSR/COO/CSC_DIA: "Offset" level type is not supported by the web tool?
CSR/CSC_ELL: I'm not sure how to express ELL in TACO. Does It have two levels of size and a singleton level?

Only COO_CSR is supported. Though the paper claims that the COO can be unsorted, the web tool only supports sorted COO. 

Where can I get the original test code? Thanks!

**Comment by stephenchouca** [comment]
Unfortunately, many of the features that were described in our PLDI 2020 paper have not yet been integrated into the main branch of TACO, since the code for our initial prototype deviated from the main branch quite a bit and was not really production-ready. Our hope is to reimplement those features in the main branch at some point, though we currently do not have a firm timeline for that.

**Comment by zhang677** [comment]
Thank you for your reply @stephenchouca! Is the code for PLDI 2020 paper open-sourced? I'm curious about the implementation details of that paper :) Thank you!

**Comment by stephenchouca** [comment]
We didn't make our paper artifact publicly available. If you want a copy though, just send me an email (you can find my email address on my [personal website](http://stephenchou.net)) and I can share it with you.
